GCC = gcc
BIBLIOTECAS =
MODULOS =

PROGRAMAS = Reto1 Reto2 Reto3 Reto4 Reto5

all: $(PROGRAMAS)

Reto1:
	$(GCC) $(MODULOS) Reto1.c -o Reto1

Reto2:
	$(GCC) $(MODULOS) Reto2.c -o Reto2

Reto3:
	$(GCC) $(MODULOS) Reto3.c -o Reto4

Reto4:
	$(GCC) $(MODULOS) Reto4.c -o Reto4

Reto5:
	$(GCC) $(MODULOS) Reto5.c -o Reto5

clear:
	rm -f $(PROGRAMAS)